config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :spots do
    resources :reservations
  end
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id' => 'users#show'

  get 'welcome/team'

  get 'welcome/project'

end

app/models/spot.rb
require 'geocoder'
class Spot < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :reservations
  has_many :users, through: :reservations
  has_one :current_reservation, class_name: 'Reservation'
  geocoded_by :address
  after_validation :geocode

  mount_uploader :picture, PictureUploader


  # before_save :address_latlon, if: ->(obj){obj.latitude.present? and obj.longitude.present?}
  # before_save :location_address, if: ->(obj){obj.address.present? and obj.address_changed?}

  # def location_address
  #   @latitude ||= Geocoder.coordinates(self.address)[0]
  #   self.latitude = @latitude
  #   @longitude ||= Geocoder.coordinates(self.address)[1]
  #   self.longitude = @longitude
  # end

  # def address_latlon
  #   coordinates = [self.latitude, self.longitude]
  #   @address ||= Geocoder.address(coordinates)
  #   self.address = @address
  # end


end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def show
    @spot = Spot.find(params[:id])
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.end_time = DateTime.now

    @spot.owner = current_user

    if @spot.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end

  def new
    @user = current_user
    @spot = Spot.new
  end

  def update
    p params
    @spot = Spot.find(params[:id]) #define variable to edit

    if params[:spot][:availability]
      @spot.assign_attributes(availability: params[:spot][:availability] == 'true') #assign new attributes
    else
      p '*' * 10
      p params[:spot][:end_time]
      p '*' * 10
      p DateTime.strptime(params[:spot][:end_time], '%m/%d/%Y %H:%M %p')
      @spot.assign_attributes(price: params[:spot][:price], end_time: DateTime.strptime(params[:spot][:end_time], '%m/%d/%Y %H:%M %p'))
    end
    p @spot
    respond_to do |format|
      if @spot.save
        # redirect_to spot_path
        format.js
      else
        redirect_to users_path(current_user)
      end
    end
  end

  private



  def spot_params
    params.require(:spot).permit(:address, :price, :end_time, :picture, :picture_cache)
  end

end

app/views/spots/_form.html.erb
<%= form_for spot do |f|  %>

<p><b>Price:</b> $<%= f.number_field :price,class: 'price', placeholder: "Price", in: 1.0..20.0, step: 1 %><p>
<b>End Time Availability:</b>
<div class='input-group date datetimepicker'>
<%= f.text_field :end_time, placeholder: "End Time", class: 'form-control' %>
<span class="input-group-addon">
  <span class="glyphicon glyphicon-calendar"></span>
</span>
</div><br><br>
<% end %>

  <script>
    var data = {'data-format': 'MM/dd/yyyy hh:mm PP' };
    $('.datetimepicker').attr(data);
    $('.datetimepicker').datetimepicker(
      // change: function() {
        // console.log("Test")
        // $(this).change();
      // }
    // ).on("input change", function(){
    //   console.log("changed date");
    // }
    // ).on("dp.hide", function(){
    //   console.log("Test")
    // }
    );
  </script>
  <style type="text/css">
    .datetimepicker{
      display: inline;
      float:left;
    }
  </style>

app/views/spots/_spot.html.erb
<br>
<div class="container">
  
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="thumbnail">
        <img src="<%= spot.picture.url %>" alt="...">
        <div class="caption">
         <div class="spot<%=spot.id%>">
          <h5><%= spot.address %></h5>
          <% if spot.current_reservation %>
            <b>EndTime: </b><span><%= spot.end_time.strftime("%m/%d/%Y %l:%M %p") %></span>
            <img src="https://rlv.zcache.com/portable_occupied_magnet-rde6bc36ed65c4b81977110bf2dc526a5_adgua_8byvr_324.jpg" class="img-responsive" alt="" style="margin:0 auto; width: 160px; height: 130px">
          <% else %>
            <% if spot.availability %>
              <p>Available</p>
            <% else %>
              <p>Unavailable</p>
            <% end %>
            <div id="toggle<%=spot.id%>" style="margin:0 auto; width: 50px"></div>
            <% if spot.availability %>
              <%= render partial: 'spots/form', locals: {spot: spot} %>
            <% end %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
	$("#toggle<%=spot.id%>").btnSwitch({
		Theme: 'Light',
		ToggleState: <%= spot.availability %>,
		OnCallback: function(){
			console.log("on");
			$.ajax({
				url: "/spots/<%= spot.id %>",
				method: "PUT",
				data: {"spot": {"availability": true}},
				success: function(res){$(this).append(res);}
			});
		},
		OffCallback: function(){
			$.ajax({
				url: "/spots/<%= spot.id %>",
				method: "PUT",
				data: {"spot": {"availability": false}}
			}).done(function(res){
				$(this).next().hide();
			});
		}
	});

  $(".spot<%=spot.id%>").on("change", ".edit_spot input", function(e){
    console.log("*****************changed**********");
    var serializedArray = $(".spot<%=spot.id%> form").serializeArray();
    var data ={};
    serializedArray.forEach(function(serialized){
	    data[serialized.name] = serialized.value;
    })
    console.log(data);
    $.ajax({
      url: '/spots/<%= spot.id %>',
      method: 'PUT',
      data: data
    }).done(function(res){
    })
  })

  $(".spot<%=spot.id%>").on("dp.hide", ".datetimepicker", function(e){
    console.log("*****************changed**********");
    var serializedArray = $(".spot<%=spot.id%> form").serializeArray();
    var data ={};
    serializedArray.forEach(function(serialized){
      data[serialized.name] = serialized.value;
    })
    console.log(data);
    $.ajax({
      url: '/spots/<%= spot.id %>',
      method: 'PUT',
      data: data
    }).done(function(res){
    })
  })

  $(".spot<%=spot.id%> .datetimepicker input").val("<%= spot.end_time.strftime("%m/%d/%Y %l:%M %p") %>")

</script>

app/views/spots/edit.html.erb
<h1>Edit Spot</h1>

<%= form_tag spot_path do %>

  <%= label_tag :price %>
  <%= text_field_tag :price %>

  <%= label_tag :end_time %>
  <%= text_field_tag :end_time %>

  <%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
<% end %>

app/views/spots/new.html.erb
<%if current_user %>

    <h1>Create Spot</h1>





        <div class="container">
            <div class="row">
                <section>
                    <div class="wizard">
                        <div class="wizard-inner">
                            <div class="connecting-line"></div>
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#step1" data-toggle="tab" title="Step 1"><span class="round-tab"><i class="glyphicon glyphicon-home"></i></span></a></li>
                                <li class="disabled"><a href="#step2" data-toggle="tab" title="Step 2"><span class="round-tab"><i class="glyphicon glyphicon-usd"></i></span></a></li>
                                <li class="disabled"><a href="#step3" data-toggle="tab" title="Step 3"><span class="round-tab"><i class="glyphicon glyphicon-picture"></i></span></a></li>
                                <li class="disabled"><a href="#complete" data-toggle="tab" title="Complete"><span class="round-tab"><i class="glyphicon glyphicon-ok"></i></span></a></li>
                            </ul>
                        </div>
                        <%= form_for @spot do |f| %>
                            <div class="tab-content">
                                <div class="tab-pane active" id="step1">
                                    <h3>Address</h3>
                                    <p><%= f.text_field :address, class: "address_field", required: true %></p>
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <button type="button" class="btn btn-primary next-step">Save and continue</button>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-pane" id="step2">
                                    <h3>Price</h3>
                                      <p>$<%= f.number_field :price, placeholder: "Price", required: true, in: 1.0..20.0, step: 1 %>/h</p>
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <button type="button" class="btn btn-default prev-step">Previous</button>
                                        </li>
                                        <li>
                                            <button type="button" class="btn btn-primary next-step">Save and continue</button>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-pane" id="step3">
                                    <h3>Upload your picture</h3>
                                    <div class="drag-area">
                                        <span class="dropMessage">+</span>
                                    </div>
                                    






                                    <p>
                                           <%= f.file_field :picture %>
                                           <%= f.hidden_field :picture_cache %>
                                    </p>
                                    <ul class="list-inline pull-right">
                                        <li>
                                            <button type="button" class="btn btn-default prev-step">Previous</button>
                                        </li>
                                        <li>
                                            <button type="button" class="btn btn-default next-step">Skip</button>
                                        </li>
                                        <li>
                                            <button type="button" class="btn btn-primary btn-info-full next-step">Save and continue</button>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-pane" id="complete">
                                    <h3>Complete</h3>
                                    <p>You have successfully completed all steps.</p>
                                    <%= f.submit "Create" %>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        <% end %>
                    </div>
                </section>
            </div>
        </div>
<% else %>
    <% controller.redirect_to new_user_registration_path %>
<% end %>

app/views/spots/show.html.erb
<!-- <h1>Spot Details</h1>
<%# if @spot.picture.url %>
  <%#= image_tag @spot.picture.url, class: 'spot-picture' %>
<%# end %>
<p>Price: <%#= @spot.price %></p>
<p>Address: <%#= @spot.address %></p>
<p>End Time: <%#= @spot.end_time %></p>
<%#= button_to 'Make a reservation', spot_reservations_path(@spot) %> -->




    <h1 style="text-align:center;">Spot Details</h1>
    <div class="container">
    <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="thumbnail">
      <img src="<%= @spot.picture.url %>">
      <div class="caption">
        <p class="papa">Price: <%= @spot.price %>/h</p>
        <p class="papa">Address: <%= @spot.address %></p>
        <p class="papa">End Time: <%= @spot.end_time.strftime("%m/%d/%Y %l:%M %p") %></p>
        <% if @spot.owner == current_user  %>
            <p style="color: red">This spot is your spot.</p>
        <% else %>
            <%= link_to 'Make a reservation', spot_reservations_path(@spot), method: :post %> 
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/spots/update.js.erb
console.log("Test");
$(".spot-list").html("<%= j(render current_user.owned_spots_ordered) %>");