config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :spots do
    resources :reservations
  end
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id' => 'users#show'

  get 'welcome/team'

  get 'welcome/project'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :owned_spots, class_name:"Spot", foreign_key: "owner_id"
  has_many :reservations
  has_many :spots, through: :reservations
  has_one :current_reservation, class_name: 'Reservation'

  def owned_spots_ordered
    self.owned_spots.order("created_at")
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end 

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, :password_confirmation)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		if current_user && current_user.id == params[:id].to_i
			@user = User.find(params[:id])
			@spots = @user.owned_spots
			if (@user.current_reservation)
				@reservation = @user.current_reservation
				gon.reservation = @reservation
				@location = @reservation.spot
				gon.latitude = @location.latitude
				gon.longitude = @location.longitude
			else
				gon.no_reservation = "none"
			end
			if request.xhr?
				latitude =  params[:latitude]
				longitude = params[:longitude]
				@parking_spots = Spot.near([latitude, longitude], 0.5).limit(4)
				@parking_spots = @parking_spots.select{|spot| spot.availability == true}
				@parking_display = render_to_string(partial: 'parking')
				@parking_selections = []
				@parking_spots.each {|spot| @parking_selections << {id: spot.id, address: spot.address, latitude: spot.latitude, longitude: spot.longitude, price: spot.price}}
				respond_to do |format|
					response = { selections: @parking_selections, display: @parking_display}
					format.json { render :json => response }
				end
			end
			@spots = @user.owned_spots
		else
			redirect_to new_user_session_path
		end
	end
end

app/views/users/_owner_show.html.erb
<!-- this is a show page for owner -->
<h4 id="left">My Spots</h4><h4 id="right" class="btn btn-primary next-step">Rent a spot</h4>


<div class="spot-list clearfix">
  <%= render current_user.owned_spots_ordered %>
</div>

app/views/users/_parking.html.erb
<% if @parking_spots.length != 0 %>
	<% @parking_spots.each do |spot| %>
  	<div class="col-sm-4" style="max-width:100%">
      <a href="/spots/<%= spot.id %>">
        <img class="steep" src="<%= spot.picture.url %>" alt="Lights" style="max-width:100%;max-height:165px;display:block;margin:0 auto">
      </a>
    	<div class="caption">
      <em><p>End Time: <%= spot.end_time.strftime("%m/%d/%Y %l:%M %p") %></p></em>
       <em>
       	<p>$<%= spot.price%>/h</p>
       </em>
       <em>
	       <p><%= spot.address%></p>
       </em>
      </div>
    </div>
	<% end %>
<% end %>

app/views/users/_renters.html.erb
<h1>Available spots</h1>
<div id="map"></div>
<div class="container_fluid">
<% if @user.current_reservation %>
  <p>All done with your errands? Tap the button below to end your reservation!</p>
  <%= button_to "End Reservation", spot_reservation_path(@location, @reservation), method: :patch %>
  <% else %>
    <% @spots.each do |spot| %>

      <div class="col-sm-4" style="max-width:100%">
        <a href="/w3images/lights.jpg">
          <img class="steep" src="http://career.iresearchnet.com/wp-content/uploads/2015/05/Model-Career.jpg" alt="Lights" style="width:100%">
        </a>
        <div class="caption">
         <em>
          <p>$<%= spot.price%></p>
         <em>
         <p><%= spot.address%></p>
        </div>
      </div>
   <% end %>
  </div>

<% end %>

app/views/users/show.html.erb
<h4 id="right" class="btn btn-primary next-step">Manage Your Spots</h4>
<div id="renter">
	<h1>Available spots</h1>
	<div id="map"></div>
	<div class="container_fluid" style="text-align:center">
		<% if @user.current_reservation %>
		<div class="container" id="right-image" style="float:right;width:50%;">
			<% if @user.current_reservation.spot.picture.url %>
			<img src="<%= @user.current_reservation.spot.picture.url %> " style="float: right;width: 100%;">
			<% end %>
		</div>
		<p class="papa"><b>Price:</b> <%= @user.current_reservation.spot.price %>/h</p>
		<p class="papa"><b>Address:</b> <%= @user.current_reservation.spot.address %></p>
		<p class="papa"><b>End Time:</b> <%= @user.current_reservation.spot.end_time.strftime("%m/%d/%Y %l:%M %p") %></p>
		<br>
		<br>
		<p>*All done with your errands? Tap the button below to end your reservation!</p>
		<%= button_to "End Reservation", spot_reservation_path(@location, @reservation), method: :patch %>
		<% else %>
		<div id="parking-spots"></div>
		<% end %>
	</div>
</div>



<div id="owner">
	<h4 id="right" class="rent-spots btn btn-primary next-step">Rent Spots</h4>
	<h1>My Spots</h1>



	<div class="spot-list clearfix">
		<%= render current_user.owned_spots_ordered %>
	</div>

</div>