config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'users/registrations' }
  # devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




  resources :spots do
    resources :reservations
  end
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id' => 'users#show'

  get 'welcome/team'

  get 'welcome/project'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	  @user = current_user
	end

	def team
	  @user = current_user
	end

	def project
	  @user = current_user
	end
end

app/views/welcome/index.html.erb
<!-- <div>
    <div id="jumbo" class="jumbotron">
        <h1>SPOTTED </h1>
        <p>Going out for a drive or driving to work, let your parking spot make some money for you. Making money has never been easier</p>
        <p><a class="btn btn-default" role="button" href="#">Learn more</a></p>
    </div>
</div> -->

<div class="simple-slider">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide" style="background-image:url(https://quoted.thezebra.com/wp-content/uploads/2015/03/o-COUPLE-DRIVING-AWAY-IN-A-CAR-facebook.jpg);"><h1 id="bold">SPOTTED </h1>
                <p id="par">Make extra money going for a drive</p></div>
                <div class="swiper-slide" style="background-image:url(http://stylevanity.com/wp-content/uploads/2013/05/portrait-of-smiling-woman-driving-convertible-with-boyfriend.jpg);"><h1 id="bold">FIND YOUR SPOT </h1>
                    <p id="par">It is right around the corner</p></div>
                    <div class="swiper-slide" style="background-image:url(https://s-media-cache-ak0.pinimg.com/originals/c6/cb/e5/c6cbe5599a8873545907e26b4f86a440.jpg);"><h1 id="bold">SMILE </h1>
                        <p id="par">Have fun with peace of mind</p></div>
                    </div>
        <!-- <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div> -->
    </div>
</div>
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-push-6 item text">
                    <h3>Spotted</h3>
                    <p>Safe and accessible parking spots</p>
                </div>
                <div class="col-md-3 col-md-pull-6 col-sm-4 item">
                    <h3>About</h3>

                    <ul>
                        <li><%= link_to 'Home', root_path %></li>
                        <li><%= link_to 'Team', welcome_team_path %></li>
                        <li><%= link_to 'Project Details', welcome_project_path %></li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Spotted © 2017</p>
        </div>
    </footer>
</div>

app/views/welcome/project.html.erb
<div class="project-grid">
	<div class="container">
		
		<br>
		<br>

		<h1 style="font-size:65px">Project Details</h1>

		<div class="row people">

			<h2 class="text-center">The Stack</h2>

			<div class="box" style="background-image:url(https://udemy-images.udemy.com/course/750x422/8082_e627_11.jpg)">
				<div class="cover">
					<h3 class="name" style="color:white;font-size:65px;padding-top:80px">Backend</h3>
				</div>
			</div>

			<div class="box" style="background-image:url(http://wakeupandcode.com/wp-content/uploads/2013/02/html5_css_javascript.png)">
				<div class="cover">
					<h3 class="name" style="font-size:65px;padding-top:80px">Frontend</h3>
				</div>
			</div>

			<div class="box" style="background-image:url(https://www.dwrl.utexas.edu/wp-content/uploads/2016/11/google-maps-new-interface1.jpg)">
				<div class="cover">
					<h3 class="name" style="color:white;font-size:65px;padding-top:80px">API</h3>
				</div>
			</div>

			<div class="box" style="background-image:url(https://www.j2store.org/images/plugins_logo/amazon_s3.png)">
			</div>

			<div class="box" style="background-image:url(https://udemy-images.udemy.com/course/750x422/193012_62e5_3.jpg)">
			</div>

			<div class="box" style="background-image:url(https://cdn2.tnwcdn.com/wp-content/blogs.dir/1/files/2015/04/twilio.jpg)">
			</div>
		</div>
	</div>

	<br>
	<br>
	<br>

	<h2 class="text-center">The Process</h2>
	<div style="width:80%;margin:0 auto" class="slider-project single-item">
		<img class="project-slide slide-image custom-image" src='/whiteboard_1.jpg'/>
		<img class="project-slide slide-image custom-image" src='/whiteboard_2.jpg'/>
		<img class="project-slide slide-image custom-image" src='/whiteboard_3.jpg'/>
		<img class="project-slide slide-image custom-image" src='/whiteboard_4.jpg'/>
		<img class="project-slide slide-image custom-image" src='/wireframe_screenshots.png'/>
		<img class="project-slide slide-image custom-image" src='/wireframe1.png'/>
		<img class="project-slide slide-image custom-image" src='/wireframe2.png'/>
		<img class="project-slide slide-image custom-image" src='/wireframe3.png'/>
	</div>
</div>

app/views/welcome/team.html.erb
<div class="team-grid">
	<div class="container">
		<div class="intro">
			<h2 class="text-center">Team</h2>
		</div>
		<div class="row people">
			<div class="col-md-3 col-sm-4 item">
				<div class="box" style="background-image:url(https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAeAAAAAJGJkOWFkNGVmLWVhODctNDRjMC1hYjJhLWQ5MzNhMDlhYTAwMw.jpg)">
					<div class="cover">
						<h3 class="name">Yusuke Takeuchi</h3>
						<p class="title">Software Samurai</p><br><br>
						<div class="social"><a href="https://www.linkedin.com/in/yusuke-takeuchi/" target="_blank"><i class="linkedin-official"><%= image_tag("linkedin_icon.png") %></i></a></div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-4 item">
				<div class="box" style="background-image:url(https://media.licdn.com/media/AAEAAQAAAAAAAAZfAAAAJGU4ZjRlNTczLTg5NjMtNDgyNS1hZmE0LTNjMDM3MjNjYzA0Mg.jpg)">
					<div class="cover">
						<h3 class="name">Derek Pham</h3>
						<p class="title">Programmer-at-Arms</p><br><br>
						<div class="social"><a href="https://www.linkedin.com/in/derekmpham/" target="_blank"><i class="linkedin-official"><%= image_tag("linkedin_icon.png") %></i></a></div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-4 item">
				<a href="https://www.linkedin.com/in/jay-naidu-706203108/"><div class="box" style="background-image:url(https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAoKAAAAJDNmMzk3MWE2LWZhZjItNDZjMi04YTVmLWJkMGQ3OWIzMDBmNA.jpg)"></a>
					<div class="cover">
						<h3 class="name">Jay Naidu</h3>
						<p class="title">Evil Genius</p><br><br>
						<div class="social"><a href="https://www.linkedin.com/in/jay-naidu-706203108/" target="_blank"><i class="linkedin-official"><%= image_tag("linkedin_icon.png") %></i></a></div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-4 item">
				<div class="box" style="background-image:url(https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAjNAAAAJGYwMzEwMjhhLTczY2UtNGFmOS1hM2Y4LTZiZDAwYzY3ZGQ0Nw.jpg)">
					<div class="cover">
						<h3 class="name">Sean Wright</h3>
						<p class="title">JavaScript Ninja</p><br><br>
						<div class="social"><a href="https://www.linkedin.com/in/seanwrightsf/" target="_blank"><i class="linkedin-official"><%= image_tag("linkedin_icon.png") %></i></a></div>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-4 item">
				<div class="box" style="background-image:url(https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAhUAAAAJDY5YjlkMzJkLWU5OTItNGJhZi1hYTU4LTY2Mzg0NTg4NWRiNA.jpg)">
					<div class="cover">
						<h3 class="name">Oladejo "Wale" Olakareem</h3>
						<p class="title">Master of Style(ing)</p><br>
						<div class="social"><a href="https://www.linkedin.com/in/oladejo/" target="_blank"><i class="linkedin-official"><%= image_tag("linkedin_icon.png") %></i></a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>